### PR TITLE
without whitespaces ^

### PR DESCRIPTION
**Pull request by Strencher**

### CODE REVIEW

**Comment by l0c4lh057** [comment]
what did even change besides `sel.filePath` instead of `sel` in the `saveFile` function?

**Comment by Strencher** [comment]
idk that was the issue why it did not worked..

**Comment by l0c4lh057** [comment]
Yeah but for changing `sel` to `sel.filePath` in two lines there is no need for 19 changed lines

**Comment by Strencher** [comment]
i just copied the function from my code to your code because my prettier adds whitespaces to it and i'm too lazy to turn him off and on again. xD

**Pull request closed without merging**
