### PR TITLE
Fix ChannelTabs for the new version of Discord

### PR DESCRIPTION
**Pull request by samfundev**

### CODE REVIEW

**Comment by 4n0nct** [comment]
thank you

**Comment by samfundev** [comment]
I've put up my fixes [here](https://gist.githubusercontent.com/samfundev/9f8ef7ad688630ea69bf5052c1415d54/raw/ChannelTabs.plugin.js), so which should automatically update in case I fix anything in the future.

**Comment by merri1400** [comment]
I hope someone does something similar for TypingIndicator, it doesn't have to be you if you're not interested though, thanks for at least taking on one of them.

**Comment by flamebalrog** [comment]
ad
I dont have the button for addin g channel to fav.Am i miss some plugins or setting?

**Comment by Crypt0Beaver** [comment]
Thanks for the fixes @samfundev !!

**Comment by l0c4lh057** [comment]
is this PR still up to date?

**Comment by samfundev** [comment]
@l0c4lh057 There was one change that wasn't in the PR, I've just added that in the latest commit.

**Comment by pounder1991** [comment]
highly appreciated @l0c4lh057 and @samfundev.

**Comment by praveen0073** [comment]
hey @samfundev, not sure if you are still around but if so, the favorites feature stopped working with discord's newest version. When we right click on any tab, doesn't open the drop down menu anymore so we can't add favorites or remove existing ones. I tried to resolve it myself but way out of my depth. Willing to pay if you have time to look into this please. 

Attached error that shows in console when I right click on a tab

channeltabs error

**Comment by praveen0073** [comment]
Hey @samfundev if you are around, it broke again :( If you are able to fix I can tip!

**Comment by TheSnorlaxBoi** [comment]
Posting this here because I don't know where else to put it

@samfundev You might be aware already, but Discord broke all the plugins again, and just wanted to know if we can expect a fix when you have the time for it ?

**Pull request merged**
