### PR TITLE
what

### PR DESCRIPTION
**Pull request by Strencher**

### CODE REVIEW

**Comment by l0c4lh057** [comment]
:clap: change :clap: log :clap:

**Comment by l0c4lh057** [comment]
this time without reverting the actual change tho

**Comment by Strencher** [comment]
its already in

**Comment by l0c4lh057** [comment]
there's a changelog entry for 2.0.4 but now it is 2.0.5 :3

**Comment by l0c4lh057** [comment]
you managed to keep the other changes :open_mouth:

**Pull request merged**
